### ISSUE TITLE
ESP8266 and Decawave

### ISSUE THREAD

**Issue by sarwadenj** [vortex314/esp_tcp#1]
Hi @vortex314 ,

I'm working on ESP8266 and Decawave IC for indoor localization. Currently i'm using  arduino pro mini with decawave.
 I tried esp12e to communicate with decawave IC but not succeed require to go in depth.
I'm looking at your repo and want to know how interface you making in between ESP8266 and Decawave and how should i move on like in which thing i have to focus on.
Also please give me brief about your repo(likely what happening in between esp and decawave).

Thanks.

**Comment by vortex314** [comment]
Hi Narasing,

I fear that I cannot help you much further. the SPI interface of the ESP8266 is badly documented.  I was able to communicate with the DWM1000, but not very reliable. Based myself on some documentation found here : http://www.eevblog.com/forum/microcontrollers/esp8266-native-spi-hardware-driver/
 
Also trying to do distance measurements with the DWM1000 requires that the microcontroller can react in a few usec. In the ESP8266 there is a lot of code interfering with the real time aspect.
So after a lot of trial and error , I just abandoned and moved to STM32.
Maybe the ESP-32S is better documented, but I've not seen anything yet.
Regards.

**Comment by vortex314** [comment]
Hi Narasing,
problem solved. With some in depth oscilloscope investigation and a lot of trial and error . :-)
Now SPI is working at 4MHZ with DWM1000. 1) SPI registers need to be set in right order or don't get set. 2) playing with some undocumented options 3) changing baudrate ( 850k instead of 115k ) of DWM1000 , because otherwise not enough time to process in ESP8266, which took 450µsec. 2.46 msec + 450 µsec > 2.6 msec timeout. 
This was a though nut to crack.

**Comment by sarwadenj** [comment]
Hi @vortex314 ,

Great man. How you  interface ESP8266 with DECAWAVE?  Also which ESP8266 sdk are you using for these code. I want definitely test and to see output coming from ESP8266.  
Also provide some link of documentation which are helpful for knowledge to know ESP8266 better as it is not good documented.
Thanks.

**Comment by vortex314** [comment]
Hi, i'm preparing the documentation. The metrics of the distance i'm reporting to an mqtt server. This i'm making configurable, so that it becomes re-usable without recompilation. I've written my own spi routines. I guess the esp8266 has a buggy spi implementation, so trial and error brought me that far + comparing with esp32 doc. Keep you posted.

**Comment by vortex314** [comment]
Ok, working almost perfect now.
I've tested it with 2 anchors and 1 tag, For testing you can just download the .bin file and deploy on a nodeMCU connected to DWM1000. A menu on the serial port, permits to configure Wifi , MQTT and DWM properties. I had to make it almost fully interrupt driven and log to the serial port at 921600 baud to avoid too much delay

**Comment by vortex314** [comment]
source code is located under the esp_mqtt project

**Comment by sarwadenj** [comment]
Hi,

-------------------------------------------------------------------------
I|12583 ESP17B8C9 -|      setup: 159 |  dwt_initialise failed
I|12584 ESP17B8C9 -|      setup: 159 |  dwt_initialise failed
-----
Soft WDT reset
ctx: cont
sp: 3fff1720 end: 3fff1a50 offset: 01b0
--------------------------------------------------------------------------
and then stack overflow happening.
Also how you made connection between ESP8266 and DWM1000?

Thanks.

**Comment by vortex314** [comment]
In the README.md you find this link : https://docs.google.com/document/d/1fxgZ6O5Crq3wHmV1OV_fEfGh67ktuzFFL1c-V1uz-TM/pub

This should provide you all the information you are looking for, let me know if you miss something.
If the DWM1000 is not connected, the system will loop on the dwt_initialise and as such create a WDT reset.
